### PR TITLE
Fixed resource conflict on FOXEERF722V2.

### LINKED ISSUE #480: FOXE-FOXEERF722V2.config config file error
### Describe the bug
Can not find the Uart, cannot setup parameters

### To Reproduce
Flash any BF since 4.1.0 to FOXEER F722 V2 and apply custom defaults, then change motor protocol to any dshot.

### Expected behavior
Configurator can connect to FC with any dshot and can see voltage.

### Flight controller configuration

# dma

Correct
dma ADC 3 0

ERROR 
dma ADC 3 1

### Setup / Versions
 
 - Flight controller: 
 
 - Other components:
 
 - How are the different components wired up:

### PR DESCRIPTION
**Pull request by mikeller**
Fixes #480.

@Johnsnow-foxeer: Can you please test this - compared to the change proposed in #482 this will not lead to a loss of performance when used with the upcoming Betaflight 4.3.

@kc10kevin: This might be a viable workaround for the MAMBAF405US and MAMBAF722 targets as well.

### CODE REVIEW

**Comment by Johnsnow-foxeer** [comment]
OK, testing

**Comment by Johnsnow-foxeer** [comment]
Not working properly 。

**Comment by mikeller** [comment]
@Johnsnow-foxeer: 

> Not working properly

With this problem description I will not be able to fix this...

**Comment by Johnsnow-foxeer** [comment]
still checking the code

**Comment by Johnsnow-foxeer** [comment]
Line 70 CHANGE to dma ADC 3 0
Line 101 DELETE set dshot_bitbang = ON and ADD set motor_pwm_protocol = DSHOT600
Fix the problems: can not find the Uart, cannot setup parameters

**Comment by mikeller** [comment]
@Johnsnow-foxeer: Please follow the instructions that you were given in https://github.com/betaflight/unified-targets/pull/483#issuecomment-893392395.

**Comment by DusKing1** [comment]
Trying to translate his gaddam shit English:

The problem is he can't even find the USB port now. So he can't even configure the FC.

**Comment by mikeller** [comment]
Thanks for translating here @DusKing1, much appreciated.

I just tested again, and the target with this modification seems to be working fine with no lockup:

```
# defaults show
# Betaflight / STM32F7X2 (S7X2) 4.0.0 Apr  4 2019 / 00:54:12 (e44f75b4a) MSP API: 1.41
# config: manufacturer_id: UNKN, board_name: FOXE-FOXEERF722V2.config, version: unknown, date: 2021-08-07T11:20:00.425Z
```

Can you please ask them to try flashing the target in this pull request again (instructions [here](https://youtu.be/gO7HyoXYYLY)), but enable 'Full chip erase' first to make sure the existing broken configuration is wiped:

image

**Comment by DusKing1** [comment]
NP, it seems that I need to teach them manually. Will do and report.

**Review by DusKing1 — APPROVED** [review]
~Tested with a real board, confirmed to work.~ Dismiss my approve, they now told me they have a problem without any detail description.

**Comment by mikeller** [comment]
Putting this on hold until the problem described in #493 has been fixed.

**Comment by haslinghuis** [comment]
Closing as inactive

**Pull request closed without merging**
