### PR TITLE
add airbot g4 aio

### PR DESCRIPTION
**Pull request by freasy**
add airbot g4 aio

### CODE REVIEW

**Comment by sugaarK** [comment]
thanks @freasy

**Review by sugaarK — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Comment by VolkerGoeschl** [comment]
MSP-OSD on LPUART1 is not working on production sample

**Comment by haslinghuis** [comment]
LPUART should work with firmware 4.5

**Comment by VolkerGoeschl** [comment]
I flashed the latest dev-build today but I can't get the DJI-O3 to show an (MSP-Display port) OSD ... or go out of low-power mode. 
IMG_20230726_121513
I already re-pinned the JST connector 6 times to rule out a TX/RX swap.

**Comment by VolkerGoeschl** [comment]
p.s.: I conformal coated the board so it will be hard for me to verify the physical connection from the G4 to the 6pin-JST :-(

**Comment by haslinghuis** [comment]
TX1 and RX1 are used for DJI O3 afaik. LPUART1 being used for ESC telemetry IIRC.
image

**Comment by VolkerGoeschl** [comment]
The TX1/RX1 pins on the JST-plug are not connected to the TX1/RX1 solder pads on the other side of the board (10V and ground are)

**Comment by haslinghuis** [comment]
Hmm, that's the only info I got. We need to ask airbot.

**Comment by freasy** [comment]
> The TX1/RX1 pins on the JST-plug are not connected to the TX1/RX1 solder pads on the other side of the board (10V and ground are)

this is a multi purpose plug, it can be used for digital and analog vtx, if you pull the second GND to GND it will switch into digital version, otherwise its a analog plug. So thats all correct here.

**Comment by VolkerGoeschl** [comment]
Thanks for the clarification - the chinese supplier couldn't give me a proper pinout.

**Pull request merged**
