### PR TITLE
Add MATEKF722MINISE target

### PR DESCRIPTION
**Pull request by TheIsotopes**
Add [Mateksys F722-miniSE](http://www.mateksys.com/?portfolio=f722-minise) target

### CODE REVIEW

**Comment by MATEKSYS** [comment]
This FC uses MatekF722mini unified target.  no need new target.

**Comment by TheIsotopes** [comment]
@MATEKSYS Yes I know.
but this is cleaned up and with `set baro_i2c_address = 118` the i2c error is also eliminated.

**Comment by MATEKSYS** [comment]
Baro address has been set to 0x76 (118) by default in this PR  https://github.com/betaflight/betaflight/pull/10129

**Comment by TheIsotopes** [comment]
Unfortunately, an i2c error occurs anyway, which can only be corrected with `set baro_i2c_address = 118` as default.

**Comment by MATEKSYS** [comment]
Normal. The errors occur during initialisation before the I2C speeds are all set up right.

**Comment by Asizon** [comment]
Latest 4.3 development version should improve initialization and i2c detected errors

**Comment by TheIsotopes** [comment]
ok then i close here.

**Pull request closed without merging**
