### PR TITLE
Fix doc link on readme

### PR DESCRIPTION
**Pull request by leocb**

### CODE REVIEW

**Comment by leocb** [comment]
Ops, didn't see there was one PR already open for this issue, closing

**Comment by mikeller** [comment]
@leocb: Feel free to re-open this and claim Hacktoberfest points for it - you discovered it independently.

**Comment by leocb** [comment]
No need, hacktoberfest count even closed PR, so I already got it
Thank you very much tho ;)

**Comment by Docteh** [comment]
I thought it wants accepted ones

**Pull request closed without merging**
