### PR TITLE
add JMI and AXIS F7 AIO

### PR DESCRIPTION
**Pull request by freasy**
add JMI and AXIS F7 AIO

### CODE REVIEW

**Review by freasy — COMMENTED** [review]
add esc_sensor feature

**Review by haslinghuis — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]
will need synchronization to https://github.com/betaflight/config

**Comment by haslinghuis** [comment]
@freasy if you have these boards then also add the config.h. Thanks.

**Comment by freasy** [comment]
Both are already present in config repo.
@haslinghuis @nerdCopter

**Pull request merged**
