### PR TITLE
Cleanup target configurations

### PR DESCRIPTION
**Pull request by haslinghuis**
Cleaning up some settings:

- set name
- feature -RX_PARALLEL_PWM is already mutual exclusive handled in firmware config.c

### CODE REVIEW

**Review by blckmn — APPROVED** [review]

**Comment by DusKing1** [comment]
> feature -RX_PARALLEL_PWM is already mutual exclusive handled in firmware config.c

Since which version?

**Comment by haslinghuis** [comment]
Most recently:
https://github.com/betaflight/betaflight/pull/9272
https://github.com/betaflight/betaflight/pull/9029

**Comment by DusKing1** [comment]
Then you shouldn't delete it from files that are based on MSP API 1.42 or earlier.

**Comment by haslinghuis** [comment]
No it was already in 3.4
https://github.com/betaflight/betaflight/pull/879

**Review by MATEKSYS — APPROVED** [review]

**Review by DusKing1 — APPROVED** [review]
Comment
> Then you shouldn't delete it from files that are based on MSP API 1.42 or earlier.

is based on
> Long before:
https://github.com/betaflight/betaflight/pull/9272
https://github.com/betaflight/betaflight/pull/9029

but if we already have it in version earlier than the first unified target then that's fine.

**Pull request merged**
