### PR TITLE
Add USE_RX_SPI to CBEE SX1280

### PR DESCRIPTION
**Pull request by blckmn**
- as feature RX_SPI not in this config

### CODE REVIEW

**Comment by haslinghuis** [comment]
@blckmn betafpv does use feature RX_SPI instead:

https://github.com/betaflight/unified-targets/blob/master/configs/default/BEFH-BETAFPVF4SX1280.config

**Comment by blckmn** [comment]
> @blckmn betafpv does use feature RX_SPI instead:
> 
> https://github.com/betaflight/unified-targets/blob/master/configs/default/BEFH-BETAFPVF4SX1280.config

yeah - I have a list of "auto included defines" based on `feature` use within the config file. This can be swapped out for `feature RX_SPI` but either works.

**Comment by blckmn** [comment]
@haslinghuis ☝️

**Comment by haslinghuis** [comment]
On betafpv RX_SPI is enabled by default. Don't have Crazybee HW for comparison.

**Pull request merged**
