### PR TITLE
Add SPRO-SPRACINGH7NANO.config

### PR DESCRIPTION
**Pull request by theojalba**
- [x] Adds unified config for SPRACING H7NANO board.

Based on SPRACING H7EXTREME config with hardware settings from BF 4.3 H7NANO config.

Related pull request:
https://github.com/betaflight/betaflight/pull/12575

### CODE REVIEW

**Comment by hydra** [comment]
This and the other PR's seem OK to me, not tested here though, but if it works for you then it'll work for me as all the boards are the same.  If all the pin definitions and such-like came from the BF 4.3 config files then the pins will be correct.  It's probably worth comparing the outputs of the various cli 'resource show' and diffs between 4.3 and 4.4/master to make sure everything is as expected.  I couldn't spot anything /obviously/ missing/wrong.

**Comment by theojalba** [comment]
> If all the pin definitions and such-like came from the BF 4.3 config files then the pins will be correct.

Yes, the NANO specific pins and other differences were identified by diff-ing BF 4.3 EXTREME with BF 4.3 NANO. These changes were then applied on top of BF 4.4 EXTREME to create BF 4.4 NANO. This was then ported to master (aka BF 4.5) with minor changes.

> It's probably worth comparing the outputs of the various cli 'resource show' and diffs between 4.3 and 4.4/master to make sure everything is as expected. I couldn't spot anything /obviously/ missing/wrong.

I re-validated the changes by comparing the diffs 4.4 EXTREME / NANO and 4.5 EXTREME / NANO with the diff BF 4.3 EXTREME / NANO to confirm that the right changes were made.

I also compared the NANO BF 4.3 resources with the BF 4.5 resources from my quad and found the following missing:


Will update to add these in.

**Comment by theojalba** [comment]
@hydra I see pins for `LED_STRIP` and `TRANSPONDER` in this NANO configuration but they are not showing up as resources when flashing the firmware. Any idea why they would go missing?

**Comment by haslinghuis** [comment]
@theojalba Add required features like `TRANSPONDER` and `LED_STRIP` in build options to retain the resources in the diff.

**Comment by theojalba** [comment]
@haslinghuis: Like this?
```make SPRACINGH7NANO EXTRA_FLAGS="-D'BUILD_KEY=afb536a7b9178b11617c47f161899c93' -D'RELEASE_NAME=4.5.0-zulu' -DCLOUD_BUILD -DUSE_DSHOT -DUSE_GPS -DUSE_GPS_PLUS_CODES -DUSE_OSD -DUSE_OSD_HD -DUSE_OSD_SD -DUSE_PINIO -DUSE_SERIALRX -DUSE_SERIALRX_CRSF -DUSE_TELEMETRY -DUSE_TELEMETRY_CRSF -DUSE_VTX -DUSE_LED_STRIP -DUSE_TRANSPONDER"```

The resources for `LED_STRIP` and `TRANSPONDER` are still not showing up.

**Comment by haslinghuis** [comment]
Yes that should work, but it does not work on H750 either (which enters DFU after cold boot) - as I'm using the 4.5 config in firmware.
Checked on MATEKH743 and it works.

**Comment by theojalba** [comment]
Ok, so do we ignore this for now for the purposes of this PR?

**Comment by haslinghuis** [comment]
Confirm now adding 
```
#define CONFIG_IN_EXTERNAL_FLASH
#define USE_FIRMWARE_PARTITION
```
to firmware 4.5 build the DFU issue is resolved. Resource `LED_STRIP` also absent :upside_down_face: 

There was no unified target for this board only a legacy target.

**Comment by theojalba** [comment]
@haslinghuis: Your findings above are for the H7EXTREME?

**Comment by haslinghuis** [comment]
Hmm. removing USE_SDCARD now I got the LED_STRIP resource shown.

**Comment by haslinghuis** [comment]
As SDCard did not show up I tried to move it to flash, and now led_strip and transponder are working. Resources show up in cli.

In the make command - the build key - should be pre build once to be useful - as configurator takes the key to decide on features.

**Review by haslinghuis — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]

**Pull request merged**
