### PR TITLE
Revert "Disable bitbang and burst dshot on HYBRIDG4"

### PR DESCRIPTION
**Pull request by haslinghuis**
Reverts betaflight/unified-targets#545

As requested in https://github.com/betaflight/betaflight/pull/11158

### CODE REVIEW

**Review by DusKing1 — APPROVED** [review]
This is not enough, NERC-NEUTRONRCG4AIO also need to remove these two lines. But I can do that.

**Comment by haslinghuis** [comment]
@DusKing1 can we merge it now?

**Review by DusKing1 — APPROVED** [review]

**Review by daleckystepan — APPROVED** [review]

**Comment by DusKing1** [comment]
do note that this should be merged after https://github.com/betaflight/betaflight/pull/11158 gets merged

**Comment by haslinghuis** [comment]
@SteveCEvans

**Review by SteveCEvans — APPROVED** [review]

**Pull request merged**
