### PR TITLE
add IFLIGHT_BLITZ_F7_PRO target

### PR DESCRIPTION
**Pull request by Guidus93**
Add the target for IFRC IFLIGHT_BLITZ_F7_PRO
@Linjieqiang Please take a look.

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]

**Comment by Linjieqiang** [comment]
I don't have this board for the time being. Did you design this board yourself? Iflight does not manufacture this board, or can you provide a schematic or a physical picture of the board? Because there may be a problem of piracy. @Guidus93

**Comment by haslinghuis** [comment]
If this is not an IFRC official board we should not support it as an IFRC target.

**Comment by Guidus93** [comment]
Hello guys, 
it's designed from IFRC, @Linjieqiang you can ask the schematic to them directly if you need.
It's an official board from them, no piracy here :) , you guys can check with IFRC if want more info.
They provided me a sample and i made the target. Here the pics of the sample:
 
IFRC_BLITZ_F7_PRO_2
IFRC_BLITZ_F7_PRO

**Comment by Si-iF** [comment]
We confirm that this is our desing and we provided sample to @Guidus93  for the target. Please proceed with the merging. 
If you want futher information please contact us at support@iflight-rc.com
@Linjieqiang  that if you need the schematic you can contact us directly. 

0d7ac2a92e8910b110aa94929e74a79
be700b3976c46a2bfa11f207d907bb9

**Comment by Si-iF** [comment]
We confirm that this is our desing and we provided sample to @Guidus93  for the target. Please proceed with the merging. 
If you want futher information please contact us at support@iflight-rc.com
@Linjieqiang  that if you need the schematic you can contact us directly. 

0d7ac2a92e8910b110aa94929e74a79
be700b3976c46a2bfa11f207d907bb9

**Comment by DusKing1** [comment]
Spamming

**Comment by Linjieqiang** [comment]
@Guidus93 @Si-iF Okay.

**Pull request merged**
