### PR TITLE
Add OMNINXT7 and BLUEJAYF4 Unified Targets

### PR DESCRIPTION
**Pull request by RipperDrone**

### CODE REVIEW

**Comment by mikeller** [comment]
@RipperDrone: Are you going to rebase this? Since you haven't allowed maintainer modifications to your pull request I cannot do this for you.

**Comment by RipperDrone** [comment]
@mikeller Ah-oh, I saw this coming ;-) It seems that out of ignorance, I have deleted my local branches in the meantime, so I need to somehow manage the code directly in/from the PR's. Still lacking the knowledge how to do that. I have watched a couple of Gitkraken tutorial videos, but still don't know exactly how to further modify these 2 target files from their current state... pls let me know what I can do from this point, the clearer you describe the steps the more likely I'm gonna be able to follow them :-)

**Comment by mikeller** [comment]
@RipperDrone: This is how you grant access to maintainers:

image

But if you deleted you fork then granting access was a red herring prompted by 'unknown repository':

image

The only way forward short of copy / pasting is to merge this as it is, which I will do. But next time, try to squash you commits before you delete your fork - or don't delete it at all. :wink:

**Comment by RipperDrone** [comment]
@mikeller thanks. Will try harder next time 👍

**Pull request merged**
