### PR TITLE
Added Unified Target for IFLIGHT_H7_TWING.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by DusKing1** [comment]
It seems that the flash chips on QUAD-SPI can not work on H743 unified target.

**Review by DusKing1 — APPROVED** [review]
It seems that the flash chips on QUAD-SPI can not work on H743 unified target. Other than that all seems to work properly.

**Comment by mikeller** [comment]
@DusKing1: Yes, unfortunately quad SPI is poor at the moment and does not properly support Unified Targets. Does the IFlight H7 TwinG have a quad SPI attached flash chip?

**Comment by DusKing1** [comment]
@mikeller AFAIK yes, it's the W25N01G, and if you have the same sample as me, on the bottom side there are only two chips, one is MAX7456 and the other one is that flash chip.

**Pull request merged**
