### PR TITLE
Fix TMOTORF7V2

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes: https://github.com/betaflight/betaflight/issues/11635

### CODE REVIEW

**Review by KarateBrot — APPROVED** [review]

**Comment by limonspb** [comment]
interesting that this did not help for this guy:
https://github.com/betaflight/betaflight/issues/11635#issuecomment-1146870568

**Comment by limonspb** [comment]
interesting that 
`set dshot_burst = OFF`
did not help to this guy:
https://github.com/betaflight/betaflight/issues/11635#issuecomment-1146870568

**Comment by KarateBrot** [comment]
@limonspb Maybe I don't get it but that's the opposite of what this PR is doing

**Comment by limonspb** [comment]
> @limonspb Maybe I don't get it but that's the opposite of what this PR is doing, so no wonder it didn't help him

oh damn you are right lol.
I gotta ask him to try ON.

**Review by KarateBrot — CHANGES_REQUESTED** [review]
I'll block this again until we get the feedback about all 8 motors working without changes, if you're ok with it.

**Comment by haslinghuis** [comment]
Will re-open if needed awaiting @Guidus93 test results using 8 motors.

**Pull request closed without merging**
