### PR TITLE
Fix dma ADC

### PR DESCRIPTION
**Pull request by apeelme**

### CODE REVIEW

**Comment by apeelme** [comment]
https://github.com/betaflight/betaflight/issues/10971

**Comment by haslinghuis** [comment]
According to my information @Guidus93 is the maintainer of this brand.

**Review by haslinghuis — APPROVED** [review]

**Comment by Guidus93** [comment]
> According to my information @Guidus93 is the maintainer of this brand.
Yeah I am. @apeelme already test this target mod?

**Comment by apeelme** [comment]
> > According to my information @Guidus93 is the maintainer of this brand.
> Yeah I am. @apeelme already test this target mod?

Yes.

**Comment by mikeller** [comment]
@haslinghuis: Not sure this should have been merged - this is reverting changes in https://github.com/betaflight/unified-targets/pull/466 that made this board capable of fully supporting SPI DMA, which now is broken again. We probably need to revert this and look into what else is broken with this target to prevent ADC from working on ADC 3 - simply breaking SPI DMA support in order to 'fix' this is not a good option.

**Comment by haslinghuis** [comment]
Merged as it was tested but I see 10573 has some ongoing work (memory overflow). If the issue is fixed we can revert anytime. Keeping an eye on it. Took note of the issue.

**Pull request merged**
