### PR TITLE
Added I2C 3 to Matek F405 boards that have it on S4 / S6.

### PR DESCRIPTION
**Pull request by mikeller**
@MATEKSYS are you ok with this change?

### CODE REVIEW

**Comment by MATEKSYS** [comment]
I don't feel the need to add I2C3 in these targets.  They all have I2C1 pads.  only F405-OSD board has no I2C1 breakout.   Although there is I2C3 definition in legacy target,  nobody use I2C3 on F405-CTR/STD/mini.

**Comment by mikeller** [comment]
@MATEKSYS:

> Although there is I2C3 definition in legacy target, nobody use I2C3 on F405-CTR/STD/mini.

Apparently some people do: betaflight/betaflight#9750 The user in question (@supersidor) has a MATEKF405-OSD, so I2C 1 is not an option.

**Comment by MATEKSYS** [comment]
I prefer to update MTKS-MATEKF405STD.config only.  so that F405-OSD can use this unified target.

**Comment by supersidor** [comment]
Thanks for efforts, will make firmware updates much easier for me

**Comment by mikeller** [comment]
@MATEKSYS: Updated.

**Comment by SnowLeopardFPV** [comment]
This change has now caused a conflict with motor 4 when using non DSHOT ESC protocols. Please see the comment I added to the bottom of [betaflight/betaflight#9750](https://github.com/betaflight/betaflight/pull/9750).

**Comment by mikeller** [comment]
@SnowLeopardFPV: Can you please open an issue in https://github.com/betaflight/betaflight/issues, and provide the information that you are asked when opening the issue. Also, please refrain from cross-posting the same information across several places - it only makes it less likely that somebody will be wanting to help you.

**Pull request merged**
