### PR TITLE
Create TCMM-TCMMF7.config

### PR DESCRIPTION
**Pull request by DMAXYANG**
This target Based on target MATEKF722SE
I change ‘set gyro_1_sensor_align = CW180FLIP’ to 'set gyro_1_sensor_align = CW180'

### CODE REVIEW

**Comment by mikeller** [comment]
@DMAXYANG: Are you the maintainer for TCMM targets?

**Comment by DMAXYANG** [comment]
Yes, I am. Thank you

**Comment by DMAXYANG** [comment]
Increase default core temperature threshold
Because my FC and VTX are integrated together, FC core temperature is very high without cooling.
Can you add code to TCMMF7.config file? 
For example:
#ifdef TCMMF7
#define CORE_TEMPERATURE_WARNING_THRESHOLD 125

**Comment by mikeller** [comment]
@DMAXYANG: This is not how it will work, as the Unified Target configurations are not source code that is compiled. But you can add the following to your target configuration:

```
set core_temp_alarm = <temperature>
```

Please note also that 125 is most likely way too high - most STM MCUs seem to develop reliability issues as soon as the reported core temperature goes above 85 C - if you set the alarm above this then your customers will experience in-air lock-ups and crashes without any prior warning - not sure this will be good for the reputation of your products.

**Comment by DMAXYANG** [comment]
@mikeller Thank you for your advice.
I tested that the core temperature during the flight was only 45 C，I will increase the cooling area

**Comment by mikeller** [comment]
@DMAXYANG:

> I tested that the core temperature during the flight was only 45 C，I will increase the cooling area

It's not uncommon to have overheating issues only when not in flight, due to the high airflow generated by the props.

**Pull request merged**
