### PR TITLE
Update Foxeer targets

### PR DESCRIPTION
**Pull request by ASDosjani**
F405 didn't used the right flash definition in my opinion that's why I replaced it with winboard.

### CODE REVIEW

**Review by limonspb — CHANGES_REQUESTED** [review]
Foxeer F7 V4 now also has MPU6000 version.
Also I guess, let's leave empty line at the end of files?

**Comment by haslinghuis** [comment]
Please add extra line

image

**Comment by ASDosjani** [comment]
> Please add extra line
> 
> image

Done

**Review by haslinghuis — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Review by sugaarK — APPROVED** [review]

**Comment by pavankmr853** [comment]
@limonspb  i need help in foxeer f7 v4 my fc not recognising it while connecting its says failed to open serial ports only entering in to dfu mode while pressing the boot button and connecting to PC shows strong red led light but not in to com mode i had video too if u give ur Instagram id I'll send it to u

**Comment by pavankmr853** [comment]
see this

**Comment by pavankmr853** [comment]
Screenshot_20230129-173723

**Comment by limonspb** [comment]
> @limonspb i need help in foxeer f7 v4 my fc not recognising it while connecting its says failed to open serial ports only entering in to dfu mode while pressing the boot button and connecting to PC shows strong red led light but not in to com mode i had video too if u give ur Instagram id I'll send it to u

this is not really correct place for users support and questions.
Betaflight has Discord, probably a better shot.
Or Facebook group as well.

**Pull request merged**
