### PR TITLE
add MTKS-MATEKF722PX.config

### PR DESCRIPTION
**Pull request by MATEKSYS**
no MAX7456 on this FC, but if no definitions for MAX7456,  Font manager will not display.

### CODE REVIEW

**Comment by Docteh** [comment]
If there is no MAX7456 chip should `max7456_spi_bus` be set to `0`?
https://github.com/betaflight/betaflight/issues/9287

**Comment by MATEKSYS** [comment]
> If there is no MAX7456 chip should `max7456_spi_bus` be set to `0`?
> [betaflight/betaflight#9287](https://github.com/betaflight/betaflight/issues/9287)
must define max7456 SPI and OSD_CS, otherwise no font manager

https://github.com/betaflight/betaflight/pull/9158

**Comment by mikeller** [comment]
Currently font uploading is only supported for the MAX7456 hardware, so there is no need to display the font manager if there is no MAX7456.

If the hardware does not have a MAX7456 then `set max7456_spi_bus = 2` is wrong.

**Comment by mikeller** [comment]
@MATEKSYS:

> FrskyOSD uses same font manager as MAX7456.
> When FrskyOSD is enabled on Uart. font will be uploaded to FrskyOSD.

No, it does not in the current version of Betaflight.

**Comment by MATEKSYS** [comment]
@mikeller it works fine in BF4.2, just no font manager if no max7456 definition.

**Comment by mikeller** [comment]
'BF4.2' is not something that is released or supported by Betaflight. If you want your hardware to work with non-Betaflight firmware then adding target configurations here is the wrong thing to do.

**Comment by MATEKSYS** [comment]
https://github.com/betaflight/betaflight/pull/9127
I have seen FrskyOSD was supported.

**Comment by mikeller** [comment]
@MATEKSYS:

- FrSky OSD will be supported by Betaflight after 4.2 has been released - there is no date set for this yet:

image

- even when Betaflight will support FrSky OSD in 4.2, FrSky is not paying us to add support for configuring their hardware to configurator, so we are not planning to do this - they will have to provide their own tooling to configure their hardware.

**Pull request closed without merging**
