### PR TITLE
Add compass support for EXF722DUAL config

### PR DESCRIPTION
**Pull request by Linjieqiang**

### CODE REVIEW

**Comment by mikeller** [comment]
@Linjieqiang: Should we also add you as the maintainer of the EXUAV targets so you can approve / merge pull requests?

**Comment by Linjieqiang** [comment]
@mikeller Forgive me for seeing your news just now. Yes, I am currently working as a maintainer for Exuav and Iflight hardware boards. If you are happy, I can of course be a maintainer to approve/merge the PRs. Thanks.

**Comment by mikeller** [comment]
@Linjieqiang: See #96.

**Comment by Linjieqiang** [comment]
@mikeller Got it. Thanks.

**Pull request merged**
