### PR TITLE
Add BMI270 to SKYSTARSF405AIO

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Review by sugaarK — APPROVED** [review]
I would have made the pr if you’d said any thing on discord @haslinghuis

**Comment by haslinghuis** [comment]
Yeah was going to - but you were first :grin:

**Review by SteveCEvans — APPROVED** [review]

**Comment by nerdCopter** [comment]
lol -- https://github.com/betaflight/unified-targets/pull/1066#issuecomment-1636357922

**Comment by nerdCopter** [comment]
doe unified-targets and config.h's allow for `#ifdef` ?  if yes, then we could define the unreleased-hardware alignment as well.

**Comment by haslinghuis** [comment]
Unified targets do not support `#ifdef`. On the other hand config.h should be capable. SPRacing is using it.

**Pull request merged**
