### PR TITLE
Update DMA stream on SPEEDYBEEF7V3

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes: https://github.com/betaflight/betaflight/issues/12965

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]

**Review by Martivip — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Comment by Martivip** [comment]
Hi ok i see that was merged to master and after clean flash to 4.4.2 an applying custom defaults still under `dump` I receiving `dma ADC 1 0` not `dmaADC 1 1`

**Comment by haslinghuis** [comment]
Probably the build is cached and not picking up changes. Try adding Acro_Trainer from Other Options to the build for example.

**Comment by Martivip** [comment]
> Probably the build is cached and not picking up changes. Try adding Acro_Trainer from Other Options to the build for example.

@haslinghuis Thank You it helps is ok, do you know how to clear that cached builds in the configurator on Mac ? I'm asking because configurator reinstallation with deleting Configurator from Application Support folder don't clear that cached builds

**Comment by haslinghuis** [comment]
Sorry build is cached -> in the cloud.

**Comment by Martivip** [comment]
> Sorry build is cached -> in the cloud.

OK but do you know any PR is addressed to resolve that issues ? because right now in case of unified_targets updates those updates are not pushed to the builds

**Comment by Martivip** [comment]
@haslinghuis or maybe in case on unified-target update admins of the cloud should remove all builds for this specific target  then users will start to caching the new ones with updated target, what do you think about that ?

**Comment by haslinghuis** [comment]
@blckmn can we invalidate cached builds in case of configuration updates?

**Comment by blckmn** [comment]
> @blckmn can we invalidate cached builds in case of configuration updates?

In terms of these unified configs, there's no need.

For the config.h it's already happening.

**Pull request merged**
