### PR TITLE
Add DPS310 to MATEKF722MINI

### PR DESCRIPTION
**Pull request by blckmn**

### CODE REVIEW

**Comment by haslinghuis** [comment]
Matek F722 MINI has official no baro.

http://www.mateksys.com/?portfolio=f722-mini#tab-id-2

As this is probably a clone board we should provide a new target.

**Comment by blckmn** [comment]
> Matek F722 MINI has official no baro.
> 
> http://www.mateksys.com/?portfolio=f722-mini#tab-id-2
> 
> As this is probably a clone board we should provide a new target.

Is there a Matek Mini with Baro, but without flash chip?

**Comment by haslinghuis** [comment]
Must definite be a clone as the F722SE MINI has baro AND 32M flash

http://www.mateksys.com/?portfolio=f722-minise#tab-id-2

Sound familiar to:  https://github.com/betaflight/unified-targets/pull/879

**Review by KarateBrot — DISMISSED** [review]

**Review by haslinghuis — APPROVED** [review]
| Target | Link | IMU | Baro | Flash |
| :-- | :-- | :-- | :-- | :-- |
| MATEKF722SE | [722-mini](http://www.mateksys.com/?portfolio=f722-mini) | MPU6000 & ICM20602 | No baro | 32MB  |
| MATEKF722MINI | [f722-minise](http://www.mateksys.com/?portfolio=f722-minise) | MPU6000 | DPS310 | 32MB  |
| MATEKF722SE | [f722-se](http://www.mateksys.com/?portfolio=f722-se) | MPU6000 & ICM20602 | BMP280 or DPS310 (I2C) | SDC |

**Review by KarateBrot — APPROVED** [review]

**Pull request merged**
