### PR TITLE
Add TMOTORVELOXF7SE

### PR DESCRIPTION
**Pull request by dengdizzy**
Add TMOTORVELOXF7SE,the FC samples will send to devs.

### CODE REVIEW

**Comment by dengdizzy** [comment]
@sugaarK Could you please review the code?

**Review by sugaarK — APPROVED** [review]
Nice to see the 42688 ok here.

**Comment by haslinghuis** [comment]
@dengdizzy also need to provide code in config repository.

**Comment by dengdizzy** [comment]
Sure,i will make a config PR.

**Comment by dengdizzy** [comment]
Config have make a PR [https://github.com/betaflight/config/pull/298](url)

**Review by KarateBrot — APPROVED** [review]

**Pull request merged**
