### PR TITLE
fix MATEKF405TE, MATEKH743 config

### PR DESCRIPTION
**Pull request by TheIsotopes**
Same reason as already discussed in #555.

**Edit:** I am still considering removing the setting `set serialrx_provider = xxxx` from all MTKS targets, which usually has to be adjusted by the user. What do the devs think of this?
Of course, the `MTKS-MATEKF411RX.config` is not affected.

### CODE REVIEW

**Review by haslinghuis — DISMISSED** [review]

**Comment by MATEKSYS** [comment]
set serialrx_provider = xxxx is needed

**Review by MATEKSYS — APPROVED** [review]

**Comment by TheIsotopes** [comment]
@MATEKSYS ok, discarded. was just a thought.

**Comment by TheIsotopes** [comment]
@MATEKSYS Overlooked entries `set serialrx_provider = SBUS` have been added.

**Review by MATEKSYS — COMMENTED** [review]
we set it to CRSF on purpose in this target

**Review by MATEKSYS — APPROVED** [review]

**Review by MATEKSYS — APPROVED** [review]

**Pull request merged**
