### PR TITLE
Update SKST-SKYSTARSF405AIO.config

### PR DESCRIPTION
**Pull request by haslinghuis**
Reference: https://github.com/betaflight/config/pull/91

### CODE REVIEW

**Review by nerdCopter — DISMISSED** [review]

**Review by howels — APPROVED** [review]

**Comment by nerdCopter** [comment]
can we retain BMI270 for those of us with prototype board?

**Comment by haslinghuis** [comment]
Nah, no support for prototypes in production. Developers can add defines themselves.

**Comment by howels** [comment]
> can we retain BMI270 for those of us with prototype board?

I did ask the vendor, they preferred for the prototype config to be replaced with the production version

**Comment by haslinghuis** [comment]
Needed a rebase because of merge conflict.

**Review by nerdCopter — APPROVED** [review]

**Comment by haslinghuis** [comment]
image

**Review by nerdCopter — APPROVED** [review]

**Review by sugaarK — APPROVED** [review]

**Pull request merged**
