### PR TITLE
Added IFlight Defender F411 

### PR DESCRIPTION
**Pull request by Guidus93**
Added Iflight RC Defender F411 unified target

### CODE REVIEW

**Comment by nerdCopter** [comment]
will need target added to https://github.com/betaflight/config as well

**Review by nerdCopter — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Comment by haslinghuis** [comment]
@Guidus93 can you do a config for 4.5 too ?

**Comment by Guidus93** [comment]
> @Guidus93 can you do a config for 4.5 too ?

Let me check, I will be out of the office for 15 days from tomorrow, let me see if I can have time today

**Comment by haslinghuis** [comment]
Yes will be back in 2 weeks myself. Can do it also if needed.

**Pull request merged**
