### PR TITLE
Update FLYWOOF745

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes: https://github.com/betaflight/betaflight/issues/12265

### CODE REVIEW

**Review by KarateBrot — APPROVED** [review]

**Comment by aviphysics** [comment]
Why was this change made to the FlywooF745 target instead of creating a new FlywooF745Hex target?

This change broke compatibility with the Flywoo Versatile F745 Pro flight controller

**Comment by sugaarK** [comment]
> Why was this change made to the FlywooF745 target instead of creating a new FlywooF745Hex target?
> 
> This change broke compatibility with the Flywoo Versatile F745 Pro flight controller

Sounds like there needs to me s f745 PRO firmware. And if your using 4.5 then this firmware is not what you’d be using you’d be using the config version

**Comment by sugaarK** [comment]
Not sure why we changed the motor mapping because of some random making an issue instead of asking the manufacturer.. this pr is obviously wrong and talking to flywhoo confirms this

**Comment by aviphysics** [comment]
> Not sure why we changed the motor mapping because of some random making an issue instead of asking the manufacturer.. ahh this is pretty old pr so long before direct contact with flywoo my mistake. I’ll make a pr to fix this shortly

Can you also take a look at the config repo? This change seemed to flow into that repo.

That said, the FlywooF745AIO config seemed to also be correctly configured for the Flywoo Versatile F745 Pro board.

**Comment by aviphysics** [comment]
> Are there two different hardware `FLYWOOF745` boards in the wild? Are there markings to determine a version? We should revert this and make an appropriate target-version, but should also seek guidance from @flywoo for such.

I'm not sure. There is at least an AIO and Hex version. There was probably some confusion created when Flywoo pulled all documentation for the Versatile F745 Pro.

**Comment by haslinghuis** [comment]
Proposal for copying current F745 target to F745HEX and update F745 with AIO motor definition is approved by Flywoo.

**Comment by aviphysics** [comment]
> Proposal for copying current F745 target to F745HEX and update F745 with AIO motor definition is approved by Flywoo.

Would you be able to help get the Versatile F745 Pro documentation reposted on the Flywoo website?

**Comment by haslinghuis** [comment]
Filed a request.

**Pull request merged**
