### PR TITLE
update readme: config repo, plus fix links

### PR DESCRIPTION
**Pull request by nerdCopter**
* update readme announcing config repo in alert/admonition format
* fix legacy links

https://github.com/nerdCopter/unified-targets/blob/20240514_manufac_link/README.md

### CODE REVIEW

**Comment by nerdCopter** [comment]
trying to use the alerts syntax, but it did not render.

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action

**Comment by haslinghuis** [comment]
Should we change 
`The instructions have been updated because Betaflight requires certification after migrating to a new build API`

**Comment by nerdCopter** [comment]
> Should we change `The instructions have been updated because Betaflight requires certification after migrating to a new build API`

sure. any suggestion?

**Comment by haslinghuis** [comment]
That was the suggestion - but have updated here:


`Instructions have been updated as Betaflight requires certification as we are migrating to a new build API.`
==> 
`Instructions have been updated as Betaflight requires certification after migrating to a new build API`

**Review by haslinghuis — APPROVED** [review]
Think this is even better :)

**Review by blckmn — APPROVED** [review]

**Pull request merged**
