### PR TITLE
add HGLR-HGLRCF411SX1280_15A.config

### PR DESCRIPTION
**Pull request by HGLRC-T**
Create HGLR-HGLRCF411SX1280_15A (include hw define)

### CODE REVIEW

**Review by nerdCopter — COMMENTED** [review]
* format seems correct.
* betaflight PR's from branch, not master.
image

**Review by haslinghuis — CHANGES_REQUESTED** [review]
Please create a feature branch for creating PR's

**Comment by HGLRC-T** [comment]
> 请创建一个用于创建 PR 的功能分支



> Please create a feature branch for creating PR's

OK，got the path wrong。--

**Comment by HGLRC-T** [comment]
> Please create a feature branch for creating PR's

ok，got the path wrong。--

**Pull request closed without merging**
