### PR TITLE
YYRC-EAGLEF722V1

### PR DESCRIPTION
**Pull request by tianv2mu0897**
hello:
        I would like to create a branch and merge it. I am very much looking forward to merging. If there are any issues with the branch, I hope you can provide suggestions; Thank you!

### CODE REVIEW

**Review by haslinghuis — COMMENTED** [review]
- Betaflight no longer accepts new unified targets. Board configurations needs to be added in https://github.com/betaflight/config
- We have no YYRC manufacturer data

See https://betaflight.com/docs/development/manufacturer/requirements-for-submission-of-targets

**Comment by tianv2mu0897** [comment]
邮件已收到，谢谢！

**Comment by tianv2mu0897** [comment]
hello:
&nbsp; &nbsp; &nbsp; &nbsp; Thank you for your reply. We are Huizhou Julong Electronic Technology Co., Ltd. The attached image shows our product; Our pilot test feedback performance is completely satisfactory; Thank you!








【天v2幕】
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "betaflight/unified-targets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月16日(星期天) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [betaflight/unified-targets] YYRC-EAGLEF722V1 (PR #1329)





 
@haslinghuis commented on this pull request.
  
Betaflight no longer accepts new unified targets. Board configurations needs to be added in https://github.com/betaflight/config
 
We have no YYRC manufacturer data
  
See https://betaflight.com/docs/development/manufacturer/requirements-for-submission-of-targets

**Comment by haslinghuis** [comment]
Is there a company website?

**Comment by tianv2mu0897** [comment]
Sorry, currently there is none available ；




【天v2幕】
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/unified-targets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月16日(星期天) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [betaflight/unified-targets] YYRC-EAGLEF722V1 (PR #1329)





 
Is there a company website?

**Comment by tianv2mu0897** [comment]
May I ask how I will request my configuration file;




【天v2幕】
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/unified-targets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月16日(星期天) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [betaflight/unified-targets] YYRC-EAGLEF722V1 (PR #1329)





 
Is there a company website?

**Comment by sugaarK** [comment]
Partnersprogrsm@betaflight.com

**Comment by tianv2mu0897** [comment]
hello:
&nbsp; &nbsp; &nbsp;I don't understand what this email address means. Can you explain it in more detail?Thank you!


【天v2幕】
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/unified-targets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月16日(星期天) 晚上11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [betaflight/unified-targets] YYRC-EAGLEF722V1 (PR #1329)





 
***@***.***

**Pull request closed without merging**
