### PR TITLE
CLRACINGF4 add W25Q128FV

### PR DESCRIPTION
**Pull request by klutvott123**
for the bardwell F4.
Not sure if we should make a clone config or not for this as I believe the FC is designed by the same person that designed the clracing FC so it's not really a clone.
Maybe it should have it's own config, but I'm not sure who's the manufacturer here. Is it JB? RDQ? clracing? lol

### CODE REVIEW

**Comment by haslinghuis** [comment]
We could call it `CLRACINGF4_SD`

**Comment by klutvott123** [comment]
then CLRACINGF4_SD would be the target for the actual clracing f4, and the bardwell f4 would continue to use CLRACINGF4. lol. doesn't seem right to me.

**Review by blckmn — APPROVED** [review]

**Comment by blckmn** [comment]
> then CLRACINGF4_SD would be the target for the actual clracing f4, and the bardwell f4 would continue to use CLRACINGF4. lol. doesn't seem right to me.

What is the bardwell F4 being marketed as? I'd be more inclined to leave CLRACINGF4 as is, and created the bardwell F4 closer to what it is being marketed as.

**Review by haslinghuis — APPROVED** [review]

**Comment by haslinghuis** [comment]
@joshuabardwell

**Pull request closed without merging**
