### PR TITLE
Add Talon defines

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Review by blckmn — APPROVED** [review]

**Review by blckmn — DISMISSED** [review]

**Comment by ASDosjani** [comment]
I think all of them uses W25Q128.

**Comment by haslinghuis** [comment]
Updated as Fusion has Winbond, can't see the chip on the V2, assuming it's the same.

**Comment by ZzyzxTek** [comment]
> Updated as Fusion has Winbond, can't see the chip on the V2, assuming it's the same.

Talon F7 V2. Seems to be a Winbond, sorry the stamping on it is not very crisp, but maybe you can read it?

image

**Comment by ZzyzxTek** [comment]
> Updated as Fusion has Winbond, can't see the chip on the V2, assuming it's the same.

Talon F7 V2. Looks to be a Windbond, maybe you can recognize the specific part number, sorry not very clear.
image

**Comment by haslinghuis** [comment]
Thanks. Seems to be correct. Same Winbond chip.

**Review by KarateBrot — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Pull request merged**
