### PR TITLE
Add LuxMiniF7

### PR DESCRIPTION
**Pull request by x4FF3**
Hi,

unified target for the LuxMiniF7.

KR

### CODE REVIEW

**Comment by mikeller** [comment]
@x4FF3: Are you going to be the maintainer for Airbot's target configurations? I can set you up so you can approve pull requests for Airbot target configurations.

**Comment by x4FF3** [comment]
@mikeller yes ill maintain them.

**Comment by mikeller** [comment]
@x4FF3: Is this hardware actually going to be sold and supported by Airbot? If not, the manufacturer id should not be 'AIRB', which in a future version of configurator will be used to direct users to Airbot's website for support.

**Comment by x4FF3** [comment]
@mikeller ill clarify it.

**Pull request merged**
