### PR TITLE
Fix ADC stream selection to allow for SPI DMA from gyro

### PR DESCRIPTION
**Pull request by SteveCEvans**
On F7 processors, when bi-directional DSHOT is enabled, depending on motor pin assignment you may see the following in https://github.com/betaflight/betaflight/pull/10705.

```
# dma show

Currently active DMA:
--------------------
DMA1 Stream 0: SDCARD_CS
DMA1 Stream 1: FREE
DMA1 Stream 2: FREE
DMA1 Stream 3: OSD_CS
DMA1 Stream 4: OSD_CS
DMA1 Stream 5: SDCARD_CS
DMA1 Stream 6: FREE
DMA1 Stream 7: FREE
DMA2 Stream 0: ADC
DMA2 Stream 1: FREE
DMA2 Stream 2: DSHOT_BITBANG 2
DMA2 Stream 3: GYRO_CS
DMA2 Stream 4: FREE
DMA2 Stream 5: FREE
DMA2 Stream 6: FREE
DMA2 Stream 7: FREE
```

Note that there is only one stream owned by GYRO_CS, but two are required for each SPI bus, one for transmit and one for receive. This is needed to support https://github.com/betaflight/betaflight/pull/10573 that follows https://github.com/betaflight/betaflight/pull/10705. To fix this issue, we can simply reassign the ADC to use an alternate stream thus.

```
# dma ADC 1 1
# dma ADC 1: changed from 0 to 1
```

Following a reboot you'll then see.

```
# dma show

Currently active DMA:
--------------------
DMA1 Stream 0: SDCARD_CS
DMA1 Stream 1: FREE
DMA1 Stream 2: FREE
DMA1 Stream 3: OSD_CS
DMA1 Stream 4: OSD_CS
DMA1 Stream 5: SDCARD_CS
DMA1 Stream 6: FREE
DMA1 Stream 7: FREE
DMA2 Stream 0: GYRO_CS
DMA2 Stream 1: FREE
DMA2 Stream 2: DSHOT_BITBANG 2
DMA2 Stream 3: GYRO_CS
DMA2 Stream 4: ADC
DMA2 Stream 5: FREE
DMA2 Stream 6: FREE
DMA2 Stream 7: FREE
```

This change is known to be needed for the MATEKF722SE and SPEEDYBEEF7V2.

### CODE REVIEW

**Comment by MATEKSYS** [comment]
"dma ADC 1 1" will conflict with S3 TM8_CH3

**Review by MATEKSYS — DISMISSED** [review]

**Comment by TheIsotopes** [comment]
@SteveCEvans This also applies to MATEKF722MINI and should also be changed there.

**Comment by SteveCEvans** [comment]
@TheIsotopes Done, thanks for the input.

I suspect the same applies to the following, as they all define `dma ADC 1 0` but I'm not able to test all these.

- AFNG-ALIENFLIGHTNGF7
- AFNG-ALIENFLIGHTNGF7_DUAL
- AFNG-ALIENFLIGHTNGF7_RX
- BEFH-BETAFPVF722
- DAFP-DARWINF722HD
- EACH-EACHINEF722
- EACH-EACHINEF722_AIO
- FLMO-GRAVITYF7
- FOSS-DRONIUSF7
- HARC-HAKRCF722
- HBRO-KAKUTEF7MINIV3
- HGLR-HGLRCF722
- HGLR-ZEUSF722_AIO
- IFRC-IFLIGHT_F745_AIO_V2
- MERA-MERAKRCF722
- MTKS-MATEKF722
- MTKS-MATEKF722HD
- NEBD-NBD_CRICKETF7
- RCTI-ARESF7
- SJET-AOCODAF722MINI
- SKZO-ATOMRCF722
- SPBE-SPEEDYBEEF7
- TCMM-TCMMF7
- TTRH-TRANSTECF7
- TTRH-TRANSTECF7HD
- YUPF-YUPIF7
- ZEEZ-ZEEZF7V2

**Comment by TheIsotopes** [comment]
@SteveCEvans After further tests this also affects the MATEKF405MINI and should be changed accordingly.

**Comment by SteveCEvans** [comment]
MATEKF405MINI updated too.

**Comment by DusKing1** [comment]
I have some samples of those FC on your list, so what's the right procedure to test this?

**Comment by SteveCEvans** [comment]
As per the opening comment, using an image from betaflight/betaflight#10573, check to see if there is only one stream with GYRO_CS as owner. Make the change to move the ADC assignment and see if you then see two GYRO_CS owned streams.

**Comment by DusKing1** [comment]
Thanks, I've notified some vendors I can reach about this PR. And I've tested on HGLRCF722 that this should fix the problem.

**Comment by SteveCEvans** [comment]
All F4 and F7 ADC 1 & 3 dma assignments moved to option 1.

**Comment by mikeller** [comment]
@SteveCEvans: Have you checked if any of the targets that you are proposing to change already use the DMA stream used by adc 1 option 1 for something else? Some of these might need more changes to resolve new resource conflicts.

**Comment by SteveCEvans** [comment]
@mikeller This change moves ADC 1 from DMA2 stream 0 channel 0 to DMA2 stream 4 channel 0 as per the below.

image

We need to free up stream 0 for SPI1_RX (again from the above) because the alternate stream 2 is typically used by bit banged DSHOT grabbing the timer channels on stream 2 thus for `TIM8_CH1` and `TIM8_CH2`.

```
# dma show

Currently active DMA:
--------------------
DMA1 Stream 0: BARO_CS
DMA1 Stream 1: FREE
DMA1 Stream 2: FREE
DMA1 Stream 3: OSD_CS
DMA1 Stream 4: OSD_CS
DMA1 Stream 5: BARO_CS
DMA1 Stream 6: FREE
DMA1 Stream 7: FREE
DMA2 Stream 0: GYRO_CS
DMA2 Stream 1: FREE
DMA2 Stream 2: DSHOT_BITBANG 3
DMA2 Stream 3: DSHOT_BITBANG 2
DMA2 Stream 4: ADC
DMA2 Stream 5: GYRO_CS
DMA2 Stream 6: LED_STRIP
DMA2 Stream 7: FREE

# dma
dma ADC 1 1
# ADC 1: DMA0 Stream 0 Channel 0
dma pin C06 1
# pin C06: DMA2 Stream 2 Channel 7
dma pin C07 1
# pin C07: DMA2 Stream 3 Channel 7
<...>
```

There is a conflict with this is for those FC's which use pin C08 for a PPM input or motor output thus:

```
dma pin C08 1
# pin C08: DMA2 Stream 4 Channel 7
```

Also the FOSS-F4BY, LEGA-VRRACE and NGUA-UAVPNG030MINI also use pin E14 thus:

```
dma pin E14 0
# pin E14: DMA2 Stream 4 Channel 6
```

I have therefore made no changes to the configuration for FCs using C08 or E14.

There are no other uses of DMA2 Stream 4.

On F4s, if bit banged DSHOT is used this ceases to be an issue anyway as the GYRO_CS won't claim ownership of the SPI1_RX and SPI1_TX streams.

The changes in this PR will prevent the conflict between ADC and GYRO_CS for F7s, and for F4s which are not using bit-banged DSHOT.

**Comment by mikeller** [comment]
@SteveCEvans: Thanks for looking into this. Not sure if I am overlooking something, but a quick search returns some more targets that are using DMA2 Stream 4 (targets without a proposed change to ADC removed):

```
mikeller@pc:~/git/unified-targets$ grep "DMA2 Stream 4" configs/default/*.config | grep -v ADC 
configs/default/AFNG-ALIENFLIGHTNGF7.config:# pin C08: DMA2 Stream 4 Channel 7
configs/default/AFNG-ALIENFLIGHTNGF7_DUAL.config:# pin C08: DMA2 Stream 4 Channel 7
configs/default/AFNG-ALIENFLIGHTNGF7_RX.config:# pin C08: DMA2 Stream 4 Channel 7
configs/default/IFRC-IFLIGHT_F745_AIO_V2.config:# pin C08: DMA2 Stream 4 Channel 7
configs/default/MTKS-MATEKF722.config:# pin C08: DMA2 Stream 4 Channel 7
configs/default/MTKS-MATEKF722HD.config:# pin C08: DMA2 Stream 4 Channel 7
configs/default/SKZO-ATOMRCF722.config:# pin C08: DMA2 Stream 4 Channel 7
configs/default/SPBE-SPEEDYBEEF7.config:# pin C08: DMA2 Stream 4 Channel 7
configs/default/YUPF-YUPIF7.config:# pin C08: DMA2 Stream 4 Channel 7
```

Do these need modifications to the resource allocation as well?

**Review by x4FF3 — APPROVED** [review]
thanks for doing this! LGTM:)

**Comment by SteveCEvans** [comment]
@mikeller I slipped up on my grepping. `grep -l "pin ...: DMA2 Stream 4 Channel ." *.config` caught them all.

**Review by mikeller — APPROVED** [review]

**Pull request merged**
