### PR TITLE
Disabled STM32F745 based targets until this Unified Target is fixed.

### PR DESCRIPTION
**Pull request by mikeller**
Mitigation for betaflight/betaflight#8908.

### CODE REVIEW

**Comment by DieHertz** [comment]
Are you sure about clracing? Mine was f722, but maybe it's an older version or something

**Comment by IvoFPV** [comment]
@mikeller CLRACING F7 is F722 we fixed that recently #12, shouldn't be disabled.

**Comment by mikeller** [comment]
Ha, turns out I'd done the fix on a stale checkout of the repository - mentally these are still _inside_ the betaflight repository and don't need a separate `git pull`> :confused: 

But anyhow, as we've got a fix now (betaflight/betaflight#8914), I don't think pulling them out and then putting them in again is needed.

**Comment by mikeller** [comment]
Closing this as betaflight/betaflight#8914 was merged.

**Pull request closed without merging**
