### PR TITLE
Foxeer AIO F745 changes

### PR DESCRIPTION
**Pull request by Asizon**
-Removed non used definitios
-Add dshot protocol since this is an Aio board
-Define sbus port

### CODE REVIEW

**Comment by Asizon** [comment]
@Johnsnow-foxeer can you check these changes please?

**Comment by Johnsnow-foxeer** [comment]
> @Johnsnow-foxeer can you check these changes please?

Yes, agreed, thank you!

**Comment by Johnsnow-foxeer** [comment]
> > @Johnsnow-foxeer can you check these changes please?
> 
> Yes, agreed, thank you!

**Comment by Johnsnow-foxeer** [comment]
> @Johnsnow-foxeer can you check these changes please?

Yes, confirmed, thank you

**Review by KarateBrot — APPROVED** [review]

**Review by Johnsnow-foxeer — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
